@startuml class_diagram
' Class declarations '
class Main
class ARSP
class Display
class SolarPanel
class Motor
class PhotoResistor

' Class relationships '
ARSP ..|> Main : uses
Motor --> ARSP : contains
SolarPanel --> ARSP : contains
Display --> ARSP : contains
PhotoResistor --> ARSP : contains

' Class functions - constructors not included'
Main : +void setup()
Main : +void loop()

Display : +void printToScreen()

SolarPanel : +float : getSolarIntensity()
SolarPanel : +float : getRequiredXOffset()
SolarPanel : +float : getRequiredYOffset()

PhotoResistor : +int : getVoltageAnalogVal()
PhotoResistor : +int : getLightIntensity()

Motor : +float : getXPolarCoordinate()
Motor : +float : getYPolarCoordinate()
Motor : void : moveXPolarCoordinates()
Motor : void : moveYPolarCoordinates()

ARSP : +void track()
ARSP : +bool maxSolarIntensity()
ARSP : +void (Display) printCurrentPowerToDisplay()
ARSP : +void (Display) printCurrentRotationToDisplay()
ARSP : +string (PhotoResistor) getBrightestDirection()

' Class attributes '
Main : -ARSP : arsp

Display : +string currentOutput

Motor : -float : xPolarCoordinate
Motor : -float : yPolarCoordinate

PhotoResistor : -int : pin

SolarPanel : -float : solarIntensity

ARSP : -Motor : xMotor
ARSP : -Motor : yMotor
ARSP : -SolarPanel : panel
ARSP : -Display : display

@enduml